// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Google Vision API key for document validation
  static const String visionApiKey = 'AIzaSyBiJXH-t5T0CPH7UiD3L1xpKXNQH0qIXLQ';
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC85lq5ZKtoYCIDwMjhLYN1JZAz-OmcMlg',
    appId: '1:817236988593:web:1146f6acba281063f10890',
    messagingSenderId: '817236988593',
    projectId: 'parish-management-615a4',
    storageBucket: 'parish-management-615a4.firebasestorage.app',
    measurementId: null, // Not needed for this app
    // Vision API key available as: DefaultFirebaseOptions.visionApiKey
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC85lq5ZKtoYCIDwMjhLYN1JZAz-OmcMlg',
    appId: '1:817236988593:android:3c2770b43d16551df10890',
    messagingSenderId: '817236988593',
    projectId: 'parish-management-615a4',
    storageBucket: 'parish-management-615a4.firebasestorage.app',
    // Vision API key available as: DefaultFirebaseOptions.visionApiKey
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85lq5ZKtoYCIDwMjhLYN1JZAz-OmcMlg',
    appId:
        '1:817236988593:ios:3c2770b43d16551df10890', // TODO: Add iOS app ID if needed
    messagingSenderId: '817236988593',
    projectId: 'parish-management-615a4',
    storageBucket: 'parish-management-615a4.firebasestorage.app',
    iosBundleId: 'ParishManagement.System', // From google-services.json
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85lq5ZKtoYCIDwMjhLYN1JZAz-OmcMlg',
    appId:
        '1:817236988593:macos:3c2770b43d16551df10890', // TODO: Add macOS app ID if needed
    messagingSenderId: '817236988593',
    projectId: 'parish-management-615a4',
    storageBucket: 'parish-management-615a4.firebasestorage.app',
    iosBundleId: 'ParishManagement.System',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC85lq5ZKtoYCIDwMjhLYN1JZAz-OmcMlg',
    appId:
        '1:817236988593:windows:3c2770b43d16551df10890', // TODO: Add Windows app ID if needed
    messagingSenderId: '817236988593',
    projectId: 'parish-management-615a4',
    storageBucket: 'parish-management-615a4.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC85lq5ZKtoYCIDwMjhLYN1JZAz-OmcMlg',
    appId:
        '1:817236988593:linux:3c2770b43d16551df10890', // TODO: Add Linux app ID if needed
    messagingSenderId: '817236988593',
    projectId: 'parish-management-615a4',
    storageBucket: 'parish-management-615a4.firebasestorage.app',
  );
}
